### ISSUE TITLE
how to close a window using the X button or the window menu.

### ISSUE THREAD

**Issue by igorquinta** [imbus/robotframework-robosapiens#10]
I can't close the window below, Any tips?

![image](https://github.com/user-attachments/assets/8777539c-cd07-4fd4-acbe-86f5d2839b2b)

**Comment by mardukbp** [comment]
I will implement a keyword ASAP.

**Comment by mardukbp** [comment]
In the picture I don't see the bottom edge of the window. Can you drag it to the top of the screen and check whether there are any buttons near the corners? Sometimes there is a Cancel button or something similar.

**Comment by igorquinta** [comment]
@mardukbp I didn't find any buttons.
![image](https://github.com/user-attachments/assets/34f12cd2-86a2-40cd-aec3-8adb42a04458)

**Comment by mardukbp** [comment]
Ok. As I said I will implement a keyword ASAP.

**Comment by mardukbp** [comment]
I just released version 2.12.0 with the new keyword Close Window.

**Comment by igorquinta** [comment]
@mardukbp  Works!! Thank you very much!!
