### ISSUE TITLE
I can't specify a table I want to interact with when I have 2 tables on the screen.

### ISSUE THREAD

**Issue by igorquinta** [imbus/robotframework-robosapiens#12]
In this example I have 2 tables on the same screen, I cannot use all the keywords available in the second table. 
I can't target the following keywords to the second table.
- Get Row Count
- Select Tab
- Select Tab Row

I can use other keywords that deal with tables, but if I have the same column names, I will have difficulty specifying which table I'm referring to.
- Double-click Cell
- Fill Cell
- Push Button Cell
- Read Cell
- Select Cell
- Select Cell Value
- Select Table Row
![image](https://github.com/user-attachments/assets/0ad411f3-eb70-4933-9ace-9a550749231f)

If it helps with the solution, I took a screenshot of the location of the second table in Scripting Traker
![image](https://github.com/user-attachments/assets/67ab2f48-64d5-40ea-902c-9579830eeb8d)

**Comment by mardukbp** [comment]
i just released version 2.13.0. All keywords that deal with tables now have an optional argument for specifying the table number: 1, 2, ...

I tested them with Dynpros that have several tables, but not with several ALV grids. Please test them :)

**Comment by igorquinta** [comment]
@mardukbp Works perfectly! Thank you!
