### ISSUE TITLE
Missing `PressF1` and `PressF4` keywords

### ISSUE THREAD

**Issue by wisenrico** [imbus/robotframework-robosapiens#2]
My configuration has a `GridView` object where I cannot edit the text inside a cell because the only way to do it is to call `PressF4` method on the element.

I noticed that the `PressF4` method could be called on the session object coming from FindById and that seems to work:

```
session.FindById(shell_id).PressF4()
```

Could this and `PressF1` be added to a new version?

**Comment by mardukbp** [comment]
In the latest version there's the keyword "Press Key Combination" which serves exactly this purpose.


Am 13. November 2023 15:28:13 MEZ schrieb Enrico Franzelli ***@***.***>:

**Comment by wisenrico** [comment]
Unfortunately, that does not work. That's maybe because the `PressF4` function is working at shell/gridview/textfield level while the `Press Key Combination` is working at window level.

From what I have seen from the code, the key is sent to the window: https://github.com/imbus/robotframework-robosapiens/blob/7d9f680837ac835525c0cd435f0ece2748b25017/robosapiens/SAPSession.cs#L408C25-L408C25

**Comment by wisenrico** [comment]
Here the documentation: https://help.sap.com/docs/sap_gui_for_windows/b47d018c3b9b45e897faf66a6c0885a8/9ff5eb87c5b94e00b3ba063ddb4e8843.html

<img width="1246" alt="image" src="https://github.com/imbus/robotframework-robosapiens/assets/59625279/35d65d0c-2354-4cc3-b59b-0de50ed45360">

**Comment by mardukbp** [comment]
That's the documentation for GuiTextedit, which is currently not supported. According to the documentation for GuiGridView, pressing these keys should work when the GridView has the focus. Try calling "Select Cell" for your cell and then "Press Key Combination".

**Comment by mardukbp** [comment]
I just published version 1.2.16, which solves this issue. First focus the cell with "Select Cell" and then call "Press Key Combination".

**Comment by wisenrico** [comment]
I can confirm this is now working! Thank you very much.
