### ISSUE TITLE
Cannot get row count for a table inside a shell

### ISSUE THREAD

**Issue by DhinaStark** [imbus/robotframework-robosapiens#3]
Hello,
I have a table that is present inside a shell content. How can i get the row count for this table. when i use Get row count its throwing the error "Could not count the rows in the table."

<img width="950" alt="image" src="https://github.com/user-attachments/assets/a48ff75d-06c7-4e9b-a885-3b41cfdc12c6">

**Comment by mardukbp** [comment]
I just released version 2.8.2. It should work now.

**Comment by DhinaStark** [comment]
Hi, I am also trying to click on a cell or select an row in one shell table. I have tried with  "Select Table Row    2" and this is error i got "The row could not be selected. The control could not be found by id." when i tried with select cell value i got this error "NotFound: The cell with the locator '0, DOCNUM' could not be found. Hints: Check the spelling, maximize the SAP window"

Please let me know which keyword i can use to click or select an row in shell table.

**Comment by mardukbp** [comment]
The error you got with Select Table Row sounds like the ID of the GuiShell changed after it was cached by RoboSAPiens. Please verify in Scripting Tracker if the ID changes. Handling this situation would require some work.

Regarding the error with Get Row Count, please try again with version 2.8.1 running robot with log level DEBUG and paste here the stack trace from the log.html file. Version 2.8.2 didn't solve the problem.

**Comment by mardukbp** [comment]
I did some research and found out how to get the table in the screenshot (transaction BD87). Next time please provide the transaction code, if it is a standard SAP transaction. That way I can try to reproduce the issue.

I was able to reproduce the issue by double-clicking on a cell of the tree table in the previous screen (which leads to the table in the screenshot) and then calling Get Row Count. Next time please provide the list of keywords you are executing. SAP and RoboSAPiens are stateful programs, which means that the order of operations matters.

I just released Version 2.9.0, which should solve the issue.

**Comment by mardukbp** [comment]
I realized that there are two ways to get to the table:

- `Double-click cell            some entry   IDocs`
- `Double-click tree element    path/to/some entry`

I just released Version 2.9.1. Now either way you should not have any problem selecting rows and cells.

**Comment by DhinaStark** [comment]
Hi Thank you for your very quick reply and the fixes. Sorry for the lack of Transaction and detailed steps will surely add them next time.

**Comment by mardukbp** [comment]
Thank you!
