### ISSUE TITLE
Keyword keeps trying indefinitely if the element is not visible

### ISSUE THREAD

**Issue by kriffx** [imbus/robotframework-robosapiens#4]
As described in the title of this issue, the keyword keeps trying to perform the action indefinitely and there is no timeout.
My question is, how can I check whether the element is present or not or at least try a certain number of times and then close?
The specific keyword I was using is Read Cell.

I even tried something like this:
```
 FOR    ${i}    IN RANGE    1    4
    TRY
        Read Cell    row_locator=1    column=Opções de liberação
        Set Test Variable    ${OpcoesLiberacaovisivel}    ${False}
        Exit For Loop
    EXCEPT  message
        Set Test Variable    ${OpcoesLiberacaovisivel}    ${True}
    END
END
```

**Comment by mardukbp** [comment]
I am working on a solution. I think it will be ready tomorrow. Will let yo know :)

**Comment by mardukbp** [comment]
I just released version 2.10.0. I completely reworked all code related to tables. Now it should either find the cell or not.

> My question is, how can I check whether the element is present or not

Please see the section "Assertions" in the documentation. You need to define a keyword `Cell should be ${state}`. I will soon add it to the documentation. In the meantime it is left as an excercise for the reader :)

**Comment by mardukbp** [comment]
I just released version 2.10.4. In the documentation under the section Assertions you will find a keyword for asserting that a cell is present.

**Comment by kriffx** [comment]
Hello @mardukbp, I apologize for the delay, but I'm not working with SAP at the moment, but I did some tests as far as I could and the asserts worked very well. I believe this should be useful for several situations both for me and other users who will use the library, so I really appreciate your work on this implementation :)

**Comment by mardukbp** [comment]
Thank you very much for taking the time to test it. And thank you for your contribution to improve RoboSAPiens!
