### ISSUE TITLE
Error using 64bit version of SAP-login 8.00

### ISSUE THREAD

**Issue by pietersmartijn** [imbus/robotframework-robosapiens#5]
Using  the 64 bit version of SAPlogon.exe on Windows 10 Enterprise I get this error message:
SAP could not be opened. Retrieving the COM class factory for component with CLSID {62341062-29BC-4DCE-A87A-DC0CB19BF230} failed due to the following error: 80040154 Klasse is niet geregistreerd (0x80040154 (REGDB_E_CLASSNOTREG)).

After deinstalling the 64bit version en installing the 32bit GUI everything works.

I have reproduced this error on 2 different windows installations.

**Comment by mardukbp** [comment]
Did you import RoboSAPiens using the 64-bit mode?

```robotframework
Library    RoboSAPiens    x64=True  
```

**Comment by pietersmartijn** [comment]
Thanks that did fix the problem.
I completely overlooked this parameter. maybe it's a good idea to add it to the 'Open SAP' keyword documentation.

**Comment by mardukbp** [comment]
Good idea! I just released version 2.9.3 with the updated documentation.
