### ISSUE TITLE
Suggestion for a keyword Click Cell or something similar

### ISSUE THREAD

**Issue by kriffx** [imbus/robotframework-robosapiens#7]
There was one occasion when I felt the need for a keyword or something similar, because it was in the approval transaction, it was a table where I would have to click on a cell to approve, but I realized that double-clicking in that situation did not work, and it was not a checkbox, so I realized that in that situation I only needed one click. So in short, is there a way to just click on that cell?

Note: I got around it by using the ENTER keyboard command, but not the SAP keyword itself, but another one, because SAP did not work in that situation.

![image](https://github.com/user-attachments/assets/7f4b4ed6-bf8d-4781-bb66-18b4f68226e1)

**Comment by mardukbp** [comment]
The keyword Push Button Cell should work. Can you try it?

**Comment by kriffx** [comment]
@mardukbp I've tried, but unfortunately it didn't work.

**Comment by mardukbp** [comment]
I am missing that column in my SAP instance. But I think the cells are of type GuiLabel, which cannot be clicked. Using the new version 2.10.0 the following should work:

```robotframework
Select Cell              Row locator   Column name
Press Key Combination    Enter
```

**Comment by mardukbp** [comment]
@kriffx Can you confirm if the cell can be clicked with the keyword sequence above?

**Comment by kriffx** [comment]
Hello @mardukbp, I apologize for the delay, but I am not working with SAP which I needed to resolve this issue at the moment, but I am using another SAP instance in a similar scenario and it apparently worked, so I appreciate the support. If it happens again or something similar, I should reopen this ticket.

**Comment by mardukbp** [comment]
Thank you for trying it out :)
