### ISSUE TITLE
Get State of Checkbox is not available

### ISSUE THREAD

**Issue by lhlhai** [imbus/robotframework-robosapiens#8]
As described in the title, I have to get the state of the checkbox checked or unchecked but I don't see any keyword to do that.

![2024-10-05_13h50_53](https://github.com/user-attachments/assets/77dfac03-4ca1-470c-8b36-807582cc9e6e)

Could you help me to provide a solution or workaround for this case.

Thank you 
A big hug from Vietnam

**Comment by igorquinta** [comment]
@lhlhai You try "Tick Checkbox" and "Untick Checkbox" ?

https://github.com/user-attachments/assets/95684989-4596-4cbf-b88c-dc8d0acfb4f4

**Comment by mardukbp** [comment]
I just released version 2.11 with the new keyword "Read Checkbox Status".

**Comment by lhlhai** [comment]
Thank you very much
