### ISSUE TITLE
How to use "Fill text field" when we have several identical locators.

### ISSUE THREAD

**Issue by igorquinta** [imbus/robotframework-robosapiens#9]
As described in the title, I can't specify a locator when I have several of the same with "Fill text field".
Any tips?

![image](https://github.com/user-attachments/assets/885b483d-856b-4863-85bf-8b1ae5dbb55d)

**Comment by mardukbp** [comment]
As described in the documentation you can build a unique locator by concatenating two locators using `>>`. For example:

```
Fill Text Field      Itinerário: >> até:
```

**Comment by igorquinta** [comment]
@mardukbp I try but not success:
Fill Text Field    Itinerário >> até    test123
Fill Text Field    Itinerário: >> até:    test123
Fill Text Field    Itinerário:  >>  até:    test123
Fill Text Field    Itinerário  >>  até    test123

![image](https://github.com/user-attachments/assets/56557b60-9146-4bbe-8edd-2bd2a7f28eac)

Did I do something wrong?

**Comment by lhlhai** [comment]
Have you tried with field name (click on text field --> Press F1 and use that name)

**Comment by mardukbp** [comment]
I just released version 2.10.2. My suggestion should work now :)

**Comment by mardukbp** [comment]
There was an error in the search logic. Please try again with 2.10.3.

**Comment by igorquinta** [comment]
Perfect @mardukbp, thank you very much!!!
![image](https://github.com/user-attachments/assets/d24fb0a9-61b0-406a-98ad-08ba7e6fa107)
